version: '3'
services:
  db:
    image: postgres:12
    container_name: postgres-auth
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PASTGRES_DB: nestjs